#!/usr/bin/env zsh
setopt notify globdots correct pushdtohome cdablevars autolist
setopt recexact longlistjobs
setopt HIST_IGNORE_DUPS
setopt prompt_subst # Enable parameter expansion, command substitution, and arithmetic expansion in the prompt
setopt nohashdirs
setopt no_beep # don't beep on error
setopt pushd_ignore_dups # don't push multiple copies of the same directory onto the directory stack
# setopt extended_glob # treat #, ~, and ^ as part of patterns for filename generation

#unsetopt menu_complete
#unsetopt flowcontrol
setopt auto_menu
#setopt complete_in_word
#setopt always_to_end

setopt append_history # Allow multiple terminal sessions to all append to one zsh command history
setopt extended_history # save timestamp of command and duration
setopt inc_append_history # Add comamnds as they are typed, don't wait until shell exit
setopt hist_expire_dups_first # when trimming history, lose oldest duplicates first
setopt hist_ignore_dups # Do not write events to history that are duplicates of previous events
setopt hist_ignore_space # remove command line from history list when first character on the line is a space
setopt hist_reduce_blanks # Remove extra blanks from each command line being added to history
#setopt hist_find_no_dups # When searching history don't display results already cycled through twice
#setopt hist_verify # don't execute, just expand history
setopt share_history # imports new commands and appends typed commands to history
